seed: 42
test_size: 0.1
batch_size: 4
dataset: both_ends_belong
model: logreg
upsample_prob: 3
project_name: ml-fraud-defi
entity: smartnets
embedding:
  num_walks: 200
  dimension: 32
  walk_length: 50
  workers: 4
  window: 10
  min_count: 1
models:
  mlp:
    hidden_layer_sizes: [100]
    max_iter: 1000
  xgb:
    num_trees: 50
    max_depth: 4
    learning_rate: 0.01
  logreg:
    C: 1.0
  epochs: 2000